LABTest/Models/FileUploadModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Web;

namespace LABTest.Models
{
    public class FileUploadModel
    {
        [Required]
        HttpPostedFileBase httpPostedFileBase { get; set; }

        public bool Uploaded { get; set; }

        public int? Leader { get; set; }

        public string Message { get; set; }
    }
}

LABTest/Controllers/FileUploadController.cs
using LABTest.App_Code;
using LABTest.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LABTest.Controllers
{
    public class FileUploadController : Controller
    {
        // GET: FileUpload/upload
        [Route("Fileupload/Upload")]
        public ActionResult Index()
        {
            FileUploadModel fileUploadModel = new FileUploadModel
            {
                Message = string.Empty,
                Leader = -1,
                Uploaded = false

            };

            return View("Upload", fileUploadModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Fileupload/Upload")]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            FileUploadModel fileModel = new FileUploadModel
            {
                Uploaded = false,
                Leader = null,
                Message = "File upload failed"
            };

            try
            {
                if (file == null)
                {
                    fileModel.Message = "No File Specified!";
                }
                else if (Path.GetExtension(file.FileName).ToLower() != ".csv")
                {
                    fileModel.Message = "File must be a CSV file!";
                }
                else if (file.ContentLength <= 0)
                {
                    fileModel.Message = "File is empty!";
                }
                else
                {
                    //Save the file
                    string saveLocation = Path.Combine(Server.MapPath("~/uploads"), file.FileName);
                    file.SaveAs(saveLocation);

                    fileModel.Message = "File Upload Complete!";
                    fileModel.Uploaded = true;
                    fileModel.Leader = LeaderClass.GetLeader(saveLocation);
                }
            }
            catch (Exception ex)
            {
                fileModel.Message = $"File Upload Failed {ex.Message}";
            }

            return View("Upload", fileModel);
        }
    }
}

LABTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LABTest.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LABTest/Views/FileUpload/Upload.cshtml
@model LABTest.Models.FileUploadModel

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <h2>Get Leader Number</h2>
    <hr />
</div>

<script>
    function showNotification(notificationType, msg) {
        toastr[notificationType](msg);
    }
</script>


@using (Html.BeginForm("Upload", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label for="upload">
            Upload CSV file:
        </label>
        <input id="File1" name="file" type="file" />
    </div>
    <input id="btnSubmit" type="submit" value="Upload file" class="btn btn-success" />

}

@if (Model.Uploaded)
{
    <div class="alert alert-success">
        <strong>Leader is: </strong>@Model.Leader
    </div>
    <script>showNotification('success', '@Model.Message')</script>
}
else if (!string.IsNullOrEmpty(Model.Message))
{
    <script>showNotification('error', '@Model.Message')</script>
}

<input id="hfFileUploaded" value="false" type="hidden" />

@section scripts{

    <script type="text/javascript">
        function showNotification(notificationType, msg) {
            toastr[notificationType](msg);
        }
    </script>
}

LABTest/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LABTest/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LABTest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "File Upload";
}

<div class="jumbotron">
    <h2>
        @Html.ActionLink("Click here to Navigate to Solution", "Upload", "FileUpload")
    </h2>
</div>

LABTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Lab Test</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LAB Test", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Solution", "Upload", "FileUpload")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer class="navbar-fixed-bottom">
            <hr />
            <p>&copy; @DateTime.Now.Year - Oluwabori Olaleye</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>